### ISSUE TITLE
Specify in README what an error in check_dump.py looks like

### ISSUE THREAD

**Issue by JacobLevinson** [vinlin24/ext2-test-suite#1]
Not a big issue just thought I'd throw my 2 cents in here. When I ran check_dump.py, I wasn't sure what I was supposed to look for, because it turned out my filesystem miraculously had no errors and there was no red. I checked against your piazza post and saw what an error would look like (red), but just thought it would be helpful to specify that anything red is an error or difference between expected output. Thanks for these scripts also!

**Comment by vinlin24** [comment]
Thanks for the tip. Copied the descriptions and demo images from [the Piazza post](https://piazza.com/class/lcjl27z4agp66l/post/407) onto the README.md.
